### ISSUE TITLE
A code sample of a command handling in the README.md

### ISSUE THREAD

**Issue by Narvalex** [m1l4n54v1c/event-store#1]
Maybe the one with the student subscribing to a course, and all of that. That would help see the BCL in acition

**Comment by m1l4n54v1c** [comment]
Hey @Narvalex ,

Thanks for sharing your interest. I've drafted up a small PR https://github.com/m1l4n54v1c/event-store/pull/2 that adds a simple sample. Any feedback is appreciated.

Cheers,
Milan
